config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard/index'
  ## super admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Api routes for leave_tracker
  namespace :api do
    namespace :v1 do
      resources :leave_trackers
    end
  end

  # Api routes for projects
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        registrations: 'registrations', sessions: 'sessions'
     }
      resources :projects
    end
  end

  # Api routes jobs
  namespace :api do
    namespace :v1 do
      resources :jobs
    end
  end

  # Api Routes
  namespace :api do
    namespace :v1 do
      resources :timesheets
    end
  end

  # Root route of the application
  root to: "dashboards#index"

  ## projects routes 
  resources :projects do 
    collection do
      get 'fetch_projects', to: 'projects#fetch_projects'
    end
  end 
  get 'users_projects/:id', to: 'projects#users_projects' 
  get 'fetch_users_projects', to: 'projects#fetch_users_projects'
  get 'projects_jobs/:id', to: 'projects#projects_jobs' 
  get 'fetch_projects_jobs', to: 'projects#fetch_projects_jobs'
  get 'projects_users/:id', to: 'projects#projects_users'
  get 'fetch_projects_users', to: 'projects#fetch_projects_users'
  get 'jobs_users/:id', to: 'jobs#jobs_users'
  get 'fetch_jobs_users', to: 'jobs#fetch_jobs_users'

  ## jobs routes 
  resources :jobs do 
    collection do 
      get 'fetch_jobs', to: 'jobs#fetch_jobs'
    end 
  end
  get 'users_jobs/:id', to: 'jobs#users_jobs' 
  get 'fetch_users_jobs', to: 'jobs#fetch_users_jobs'
  
  #in routes
  devise_for :users,:controllers =>  {  
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Routes for Employee module
  resources :users, only: [:index, :new, :edit, :destroy, :update]
  get 'fetch_employees', to: 'users#fetch_employees'
  post 'signup', to: 'users#create'
  put  'updateuser', to: 'users#update'

  # Routes for Configuration module
  resources :global_configurations
  post 'global_configurations/update_config_value', to: "global_configurations#update_config_value"
    

  # Routes for timesheets module
  resources :timesheets do
    collection do
      get '/fetch_timesheets', to: 'timesheets#fetch_timesheets'
    end
  end
  get '/fetch_timesheets', to: 'timesheets#fetch_timesheets'
  patch '/timesheet/:id' , to: 'timesheets#approve_reject' 

  # LeaveTracker routes
  resources :leave_trackers
  get '/fetch_leaves', to: 'leave_trackers#fetch_leaves' 
  get '/fetch_leaveapplication', to: 'leave_trackers#fetch_leaveapplication'
  patch '/fetch_leaveapplication/:id', to: 'leave_trackers#approve_reject'
  
  #dashboard routes
  get 'dashboards', to: 'dashboards#index'

  namespace :api, :path => 'api', :defaults => {:format => :json} do
    namespace :v1 do
      resources :users, only: [:index, :create]
    end
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  is_active  :boolean          not null
#  project_id :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Job < ApplicationRecord
  ## Associations
  belongs_to :project
  has_and_belongs_to_many :users
  has_many :timesheets , dependent: :destroy

  def as_json 
    response = super 
    response.merge!(project_name: self.project.name,user_name: self.users.select(:first_name).pluck(:first_name))
    response.merge!(users_count: self.users.count)
  end 
end

app/controllers/api/v1/jobs_controller.rb
class Api::V1::JobsController < ApplicationController 
  before_action :set_job, only: [:update, :show, :destroy]

  def index 
    jobs = Job.all
  end 

  def create 
    @job = Job.new(jobs_params)
    if @job.save 
      render_success 200, true, 'Job created successfully.', @job.as_json
    else  
      if @job.errors
        errors = @job.errors.full_messages.join(", ")
      else 
        errors = 'Job creation failed'
      end 
    end 
  end 

  def update 
    if @job.update(jobs_params)
      render_success 200, true, 'Job updated successfully', @job.as_json
    else
      if @job.errors
        errors = @job.errors.full_messages.join(", ")
      else
        errors = 'Job update failed'
      end

      return_error 500, false, errors, {}
    end
  end 

  def destroy 
    @job.destroy 
    render_success 200, true, 'Job deleted successfully.'
  end 

  def show 
    render_success 200, true, 'Job fetch sucessfully.', @job.as_json
  end 
  private 
  def jobs_params 
    params.require(:job).permit(:name, :is_active, :project_id, user_ids: [])
  end 

  def set_job 
    @job = Job.find(params[:id])
  end 
end 

app/controllers/jobs_controller.rb
  class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index 
  end 

  def fetch_jobs 
    if current_user.emp_admin? 
      jobs = Job.all.order(created_at:"desc")
    else 
      jobs = current_user.jobs.order(created_at:"desc")
    end 
    search_string = []

    # Check if Search Keyword is Present & Write it's Query
    if params.has_key?('search') && params[:search].has_key?('value') && params[:search][:value].present?
      search_columns.each do |term|
        search_string << "#{term} ILIKE :search"
      end
      jobs = jobs.where(search_string.join(' OR '), search: "%#{params[:search][:value]}%")
    end

    jobs = jobs.page(datatable_page).per(datatable_per_page)
    render json: {
      jobs: jobs.as_json,
      recordsTotal: jobs.count,
      recordsFiltered: jobs.total_count
    }
  end 

  def users_jobs 
    @userid = params[:id]
  end

  def fetch_users_jobs 
    @user = User.find_by(params[:id])
    users_jobs = @user.jobs if @user.present?
    jobs = User.find(params[:userid]).jobs.order(created_at:"desc")
    search_string = []

    # Check if Search Keyword is Present & Write it's Query
    if params.has_key?('search') && params[:search].has_key?('value') && params[:search][:value].present?
      search_columns.each do |term|
        search_string << "#{term} ILIKE :search"
      end
      jobs = jobs.where(search_string.join(' OR '), search: "%#{params[:search][:value]}%")
    end

    jobs = jobs.page(datatable_page).per(datatable_per_page)
    render json: {
      jobs: jobs.as_json,
      recordsTotal: jobs.count,
      recordsFiltered: jobs.total_count
    }
  end 

  def jobs_users 
    @jobid = params[:id]
  end 

  def fetch_jobs_users 
    @job = Job.find_by(params[:id])
    jobs_users = @job.users if @job.present?
    users = Job.find(params[:jobid]).users.order(created_at:"desc")
    search_string = []

    # Check if Search Keyword is Present & Write it's Query
    if params.has_key?('search') && params[:search].has_key?('value') && params[:search][:value].present?
      search_columns.each do |term|
        search_string << "#{term} ILIKE :search"
      end
      users = users.where(search_string.join(' OR '), search: "%#{params[:search][:value]}%")
    end

    users = users.page(datatable_page).per(datatable_per_page)
    render json: {
      users: users.as_json,
      recordsTotal: users.count,
      recordsFiltered: users.total_count
    }
  end 

  def new 
    @job = Job.new
  end 

  def create 
    @job = Job.new(jobs_create_params)
    if @job.save 
      redirect_to(jobs_url, :notice => 'Job was sucessfully added.')
    else
      format.html{ render :new , status: :unprocessable_entity }
    end 
  end 

  def update 
    if @job.update(jobs_update_params)
      JobCreatedMailer.job_assign(@job).deliver
      redirect_to jobs_path
    else  
      redirect_to root_path 
    end
    authorize! :read, @job
  end 

  def show 
    redirect_to users_url
  end 

  def destroy 
    @job.destroy
    flash[:notice] = "Job was destroy sucessfully."
    respond_to do |format|
      format.html { redirect_to jobs_url }
    end
    authorize! :read, @job
  end 
  private 

  def set_job 
    @job = Job.find(params[:id])
  end 

  def jobs_create_params 
    params.require(:job).permit(:name, :is_active, :project_id)
  end 

  def jobs_update_params 
    params.require(:job).permit(:name, :is_active, :project_id,user_ids: [])
  end 
end

app/helpers/jobs_helper.rb
module JobsHelper
  def action_text
    if controller.action_name == "new"
       return "Add Job"
    elsif controller.action_name == "edit"
       return "Update Job"
    else
       return "Submit"
    end
  end
end

app/views/jobs/_form.html.erb
<div class="card-body">
  <%= form_with(class: 'job-form', model: (@job), local: true) do |f|%>
    <div class="row mb-3">
      <label class="col-sm-2 col-form-label" for="basic-icon-default-name">Name</label>
        <div class="col-sm-10">
          <div class="input-group input-group-merge">
            <span id="basic-icon-default-name2" class="input-group-text">
            <i class="bx bx-code-block"></i></span>
              <%= f.text_field :name, id:"basic-icon-default-name", class:"form-control", placeholder: "Enter Job Name", data: {error: "#errName"} %>
          </div>
            <span id="errName"></span>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-2 form-label">Status</label>
          <div class="col-sm-10">
            <%= f.check_box :is_active, class:"form-check-input", id:"status", data: {error: "#errStatus"} %>
          <label class="form-check-label" for="status">Active</label>
          </div>
            <span id="errStatus"></span>
      </div>
      <div class="row mb-3">
        <%= f.label "Project",class:"col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <div class="input-group input-group-merge">
              <%= f.collection_select(:project_id, Project.all, :id, :name, { :prompt => 'All Projects', :selected => @job.project_id }, { class: 'form-control select-projects', data: {error: "#errSelectProject"} }) %>
          </div>
            <span id="errSelectProject"></span>
        </div>
      </div>
      <div class="row justify-content-end">
        <div class="col-sm-10">
            <%= f.submit action_text, class:'btn btn-primary'%>
        </div>
        <div class="col-sm-3 project-back-btn">
            <%= link_to 'Back', jobs_path, class:'btn btn-primary mb-2' %>
        </div>
  <% end %>
</div>

app/views/jobs/edit.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4">Edit Job</h4>
    <div class="row">
      <div class="col-xxl">
        <div class="card mb-4">
          <div class="card-body">
            <%= form_with(class: 'job-form', model: (@job), local: true) do |f|%>
              <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="basic-icon-default-name">Name</label>
                  <div class="col-sm-10">
                    <div class="input-group input-group-merge">
                      <span id="basic-icon-default-name2" class="input-group-text">
                      <i class="bx bx-code-block"></i></span>
                        <%= f.text_field :name, id:"basic-icon-default-name", class:"form-control", placeholder: "Enter Job Name", data: {error: "#errName"} %>
                    </div>
                      <span id="errName"></span>
                  </div>
              </div>
              <div class="row mb-3">
                  <label class="col-sm-2 form-label">Status</label>
                    <div class="col-sm-10">
                      <%= f.check_box :is_active, class:"form-check-input", id:"status", data: {error: "#errStatus"} %>
                    <label class="form-check-label" for="status">Active</label>
                    </div>
                      <span id="errStatus"></span>
                </div>
                <div class="row mb-3">
                  <%= f.label "Project",class:"col-sm-2 col-form-label" %>
                  <div class="col-sm-10">
                    <div class="input-group input-group-merge">
                        <%= f.collection_select(:project_id, Project.all, :id, :name, { :prompt => 'All Projects', :selected => @job.project_id }, { class: 'form-control select-projects', data: {error: "#errSelectProject"} }) %>
                    </div>
                      <span id="errSelectProject"></span>
                  </div>
                </div>
                <div class="row mb-3">
                  <label class="col-sm-2 col-form-label" for="html5-select-users">Assign To</label>
                    <div class="col-sm-10">
                      <div class="input-group input-group-merge" id="html5-select-users">
                        <%= f.collection_select(:user_ids, User.all, :id, :first_name, { :prompt => 'Select an Employees' }, { class: 'form-control select-users',multiple: true, data: {error: "#errSelectEmployees"} }) %>
                      </div>
                        <span id="errSelectEmployees"></span>
                    </div>
                </div>
                <div class="row justify-content-end">
                  <div class="col-sm-10">
                      <%= f.submit action_text, class:'btn btn-primary'%>
                  </div>
                  <div class="col-sm-3 project-back-btn">
                      <%= link_to 'Back', jobs_path, class:'btn btn-primary mb-2' %>
                  </div>
            <% end %>
          </div>
        </div>
      </div>
    </div> 
  </div> 
</div>

app/views/jobs/index.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
      <h5 class="card-header">Jobs</h5>
      <div class="table-responsive text-nowrap">
        <div class="col">
          <h4 class="fw-bold float-end m-3"><span class="text-muted fw-light"><a href='/jobs/new' class="btn btn-primary mt-1 mb-2 shared-add-btn"><i class='bx bx-plus'></i><span>Add job</span></a></h4>
        </div>
        <table class="table" id="jobs-list" data-userrole="<%= current_user.role %>">
          <caption class="ms-4">
            List of Jobs
          </caption>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/jobs/jobs_users.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
      <h5 class="card-header">Users</h5>
      <div class="table-responsive text-nowrap">
      <%= link_to 'Job Listing', jobs_path, class:"btn btn-primary mb-3 project-btn"%>
        <table class="table" id="jobs-users-list" data-source="<%= fetch_jobs_users_path(format: :json, jobid: @jobid) %>">
          <caption class="ms-4">
            List of Job Users
          </caption>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4">Add Job</h4>
    <div class="row">
      <div class="col-xxl">
        <div class="card mb-4">
          <%= render 'form' %>
        </div>
      </div>
    </div> 
  </div> 
</div>

app/views/jobs/users_jobs.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
      <h4 class="fw-bold py-3 mb-2"><span class="text-muted fw-light"><%= link_to('Employees Listing', users_path, class: 'btn btn-primary float-end') %></h4>
      <h5 class="card-header">Jobs</h5>
      <div class="table-responsive text-nowrap">
        <table class="table" id="users-jobs-list" data-source="<%= fetch_users_jobs_path(format: :json, userid: @userid) %>" >
          <caption class="ms-4">
            List of Users Jobs
          </caption>
        </table>
      </div>
    </div>
  </div>
</div>