config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard/index'
  ## super admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Api routes for leave_tracker
  namespace :api do
    namespace :v1 do
      resources :leave_trackers
    end
  end

  # Api routes for projects
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        registrations: 'registrations', sessions: 'sessions'
     }
      resources :projects
    end
  end

  # Api routes jobs
  namespace :api do
    namespace :v1 do
      resources :jobs
    end
  end

  # Api Routes
  namespace :api do
    namespace :v1 do
      resources :timesheets
    end
  end

  # Root route of the application
  root to: "dashboards#index"

  ## projects routes 
  resources :projects do 
    collection do
      get 'fetch_projects', to: 'projects#fetch_projects'
    end
  end 
  get 'users_projects/:id', to: 'projects#users_projects' 
  get 'fetch_users_projects', to: 'projects#fetch_users_projects'
  get 'projects_jobs/:id', to: 'projects#projects_jobs' 
  get 'fetch_projects_jobs', to: 'projects#fetch_projects_jobs'
  get 'projects_users/:id', to: 'projects#projects_users'
  get 'fetch_projects_users', to: 'projects#fetch_projects_users'
  get 'jobs_users/:id', to: 'jobs#jobs_users'
  get 'fetch_jobs_users', to: 'jobs#fetch_jobs_users'

  ## jobs routes 
  resources :jobs do 
    collection do 
      get 'fetch_jobs', to: 'jobs#fetch_jobs'
    end 
  end
  get 'users_jobs/:id', to: 'jobs#users_jobs' 
  get 'fetch_users_jobs', to: 'jobs#fetch_users_jobs'
  
  #in routes
  devise_for :users,:controllers =>  {  
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Routes for Employee module
  resources :users, only: [:index, :new, :edit, :destroy, :update]
  get 'fetch_employees', to: 'users#fetch_employees'
  post 'signup', to: 'users#create'
  put  'updateuser', to: 'users#update'

  # Routes for Configuration module
  resources :global_configurations
  post 'global_configurations/update_config_value', to: "global_configurations#update_config_value"
    

  # Routes for timesheets module
  resources :timesheets do
    collection do
      get '/fetch_timesheets', to: 'timesheets#fetch_timesheets'
    end
  end
  get '/fetch_timesheets', to: 'timesheets#fetch_timesheets'
  patch '/timesheet/:id' , to: 'timesheets#approve_reject' 

  # LeaveTracker routes
  resources :leave_trackers
  get '/fetch_leaves', to: 'leave_trackers#fetch_leaves' 
  get '/fetch_leaveapplication', to: 'leave_trackers#fetch_leaveapplication'
  patch '/fetch_leaveapplication/:id', to: 'leave_trackers#approve_reject'
  
  #dashboard routes
  get 'dashboards', to: 'dashboards#index'

  namespace :api, :path => 'api', :defaults => {:format => :json} do
    namespace :v1 do
      resources :users, only: [:index, :create]
    end
  end
end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h5 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved </h5>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
<% end %>   

app/views/shared/_footer.html.erb
<footer class="content-footer footer bg-footer-theme">
  <div class="container-xxl flex-wrap justify-content-between py-2 flex-md-row flex-column">
      <div class="mb-2 float-end">
          Copyright @2022
      </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<head>
  <title>Dashboard - Analytics | Sneat - Bootstrap 5 HTML Admin Template - Pro</title>
</head>

app/views/shared/_messages.html.erb
<% flash.each do|name, msg| %>
  <% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= msg %>   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end%>

app/views/shared/_sidebar.html.erb
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
  <div class="app-brand demo">
    <a href="index.html" class="app-brand-link">
      <span class="app-brand-logo demo">
        <svg
          width="25"
          viewBox="0 0 25 42"
          version="1.1"
          xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
        >
          <defs>
            <path
              d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
              id="path-1"
            ></path>
            <path
              d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
              id="path-3"
            ></path>
            <path
              d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
              id="path-4"
            ></path>
            <path
              d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
              id="path-5"
            ></path>
          </defs>
          <g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
              <g id="Icon" transform="translate(27.000000, 15.000000)">
                <g id="Mask" transform="translate(0.000000, 8.000000)">
                  <mask id="mask-2" fill="white">
                    <use xlink:href="#path-1"></use>
                  </mask>
                  <use fill="#696cff" xlink:href="#path-1"></use>
                  <g id="Path-3" mask="url(#mask-2)">
                    <use fill="#696cff" xlink:href="#path-3"></use>
                    <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
                  </g>
                  <g id="Path-4" mask="url(#mask-2)">
                    <use fill="#696cff" xlink:href="#path-4"></use>
                    <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
                  </g>
                </g>
                <g
                  id="Triangle"
                  transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) "
                >
                  <use fill="#696cff" xlink:href="#path-5"></use>
                  <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
                </g>
              </g>
            </g>
          </g>
        </svg>
      </span>
      <span class="app-brand-text demo menu-text fw-bolder ms-2">EMS</span>
    </a>

    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
      <i class="bx bx-chevron-left bx-sm align-middle"></i>
    </a>
  </div>

  <div class="menu-inner-shadow"></div>

  <ul class="menu-item">
    <!-- Dashboard -->
    <li>
      <%= link_to dashboards_path , class:"menu-link" do %>
      <i class="menu-icon tf-icons bx bx-home-circle"></i>
      <div data-i18n="Analytics">Dashboard</div>
      <% end %>
    </li>
    <% if current_user.emp_admin? %>
    <li class="mm-active">
      <a href="javascript:void(0);" data-toggle="collapse"  class="collapsible menu-link menu-toggle">
      <i class="menu-icon tf-icons bx bxs-business"></i> 
      Company
      </a>
      <ul class="menu-sub">
        <li class="menu-item">
          <%= link_to 'Company Configuration', global_configurations_path ,class:"menu-link"%>
        </li>
        <li class="menu-item">
          <%= link_to 'Projects', projects_path ,class:"menu-link"%>
        </li>
        <li class="menu-item">
          <%= link_to 'Jobs', jobs_path ,class:"menu-link"%>
        </li>
        <li class="menu-item">
          <%= link_to('Employees', users_path, class: 'menu-link') %>
        </li>
      </ul>
    </li>
    <% end %>
    <% if current_user.employee? %>
      <li class="menu-item">
        <%= link_to projects_path , class:"menu-link" do %>
          <i class="menu-icon tf-icons bx bxs-component" style="color:rgba(51,51,45,0.67)"></i>
          <div data-i18n="Account Settings">My Projects</div>
        <% end %>
      </li> 
      <li class="menu-item">
        <%= link_to jobs_path , class:"menu-link" do %>
          <i class="menu-icon tf-icons bx bxs-briefcase"></i>
          <div data-i18n="Account Settings">My Jobs</div>
        <% end %>
      </li>
      <% end %>

      <li class="menu-item">
        <%= link_to timesheets_path , class:"menu-link" do %>
          <i class="menu-icon tf-icons bx bxs-time-five"></i>
          <div data-i18n="Account Settings">Timesheet</div>
        <% end %>
      </li>
      <li class="menu-item">
        <%= link_to leave_trackers_path , class:"menu-link" do %>
          <i class="menu-icon tf-icons bx bxs-widget"></i>
          <div data-i18n="Account Settings">Leave Application</div>
        <% end %>
      </li>     
  </ul>
</aside>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;
for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>