config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard/index'
  ## super admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Api routes for leave_tracker
  namespace :api do
    namespace :v1 do
      resources :leave_trackers
    end
  end

  # Api routes for projects
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        registrations: 'registrations', sessions: 'sessions'
     }
      resources :projects
    end
  end

  # Api routes jobs
  namespace :api do
    namespace :v1 do
      resources :jobs
    end
  end

  # Api Routes
  namespace :api do
    namespace :v1 do
      resources :timesheets
    end
  end

  # Root route of the application
  root to: "dashboards#index"

  ## projects routes 
  resources :projects do 
    collection do
      get 'fetch_projects', to: 'projects#fetch_projects'
    end
  end 
  get 'users_projects/:id', to: 'projects#users_projects' 
  get 'fetch_users_projects', to: 'projects#fetch_users_projects'
  get 'projects_jobs/:id', to: 'projects#projects_jobs' 
  get 'fetch_projects_jobs', to: 'projects#fetch_projects_jobs'
  get 'projects_users/:id', to: 'projects#projects_users'
  get 'fetch_projects_users', to: 'projects#fetch_projects_users'
  get 'jobs_users/:id', to: 'jobs#jobs_users'
  get 'fetch_jobs_users', to: 'jobs#fetch_jobs_users'

  ## jobs routes 
  resources :jobs do 
    collection do 
      get 'fetch_jobs', to: 'jobs#fetch_jobs'
    end 
  end
  get 'users_jobs/:id', to: 'jobs#users_jobs' 
  get 'fetch_users_jobs', to: 'jobs#fetch_users_jobs'
  
  #in routes
  devise_for :users,:controllers =>  {  
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Routes for Employee module
  resources :users, only: [:index, :new, :edit, :destroy, :update]
  get 'fetch_employees', to: 'users#fetch_employees'
  post 'signup', to: 'users#create'
  put  'updateuser', to: 'users#update'

  # Routes for Configuration module
  resources :global_configurations
  post 'global_configurations/update_config_value', to: "global_configurations#update_config_value"
    

  # Routes for timesheets module
  resources :timesheets do
    collection do
      get '/fetch_timesheets', to: 'timesheets#fetch_timesheets'
    end
  end
  get '/fetch_timesheets', to: 'timesheets#fetch_timesheets'
  patch '/timesheet/:id' , to: 'timesheets#approve_reject' 

  # LeaveTracker routes
  resources :leave_trackers
  get '/fetch_leaves', to: 'leave_trackers#fetch_leaves' 
  get '/fetch_leaveapplication', to: 'leave_trackers#fetch_leaveapplication'
  patch '/fetch_leaveapplication/:id', to: 'leave_trackers#approve_reject'
  
  #dashboard routes
  get 'dashboards', to: 'dashboards#index'

  namespace :api, :path => 'api', :defaults => {:format => :json} do
    namespace :v1 do
      resources :users, only: [:index, :create]
    end
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  start_date :date             not null
#  end_date   :date
#  is_active  :boolean          default(TRUE)
#  company_id :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Project < ApplicationRecord
  ## Associations
  belongs_to :company
  has_and_belongs_to_many :users
  has_many :jobs , dependent: :destroy
  has_many :timesheets , dependent: :destroy

  ## Validations
  validates :name, :start_date, presence: true 

  scope :user_role, -> { User.where(role:1) }

  ## json resposne
  def as_json 
    response = super
    response.merge!(user_name: self.users.select(:first_name).pluck(:first_name))
    response.merge!(jobs: self.jobs.select(:name).pluck(:name))
    response.merge!(jobs_count: self.jobs.count)
    response.merge!(users_count: self.users.count)
    response
  end 
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < ApplicationController 
  before_action :set_project, only: [:update, :show, :destroy]

  def index 
    projects = Project.all
    render_success 200, true, 'Projects fetched successfully', projects.as_json
  end  

  def create 
    @project = Project.new(projects_params)
    if @project.save
      render_success 200, true, 'Project created successfully', @project.as_json
    else
      if @project.errors
        errors = @project.errors.full_messages.join(", ")
      else
        errors = 'Project creation failed'
      end

      return_error 500, false, errors, {}
    end
  end 

  def update 
    if @project.update(projects_params)
      render_success 200, true, 'Project updated successfully', @project.as_json
    else
      if @project.errors
        errors = @project.errors.full_messages.join(", ")
      else
        errors = 'Project update failed'
      end

      return_error 500, false, errors, {}
    end
  end 

  def destroy 
    @project.destroy
    
    render_success 200, true, 'Project deleted successfully', {}
  end 

  def show 
    render_success 200, true, 'Project fetched successfully', @@project.as_json
  end 
  
  private 
  def projects_params 
    params.require(:project).permit(:name, :start_date, :end_date, :is_active, :company_id, user_ids:[])
  end 

  def set_project 
    @project = Project.find(params[:id])
  end 
end 

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:edit, :update, :destroy]

  def index
    @project = Project.find_by(params[:id])
  end 

  def fetch_projects 
    if current_user.emp_admin? 
     projects = Project.all.order(created_at:"desc")
    else 
      projects = current_user.projects.order(created_at:"desc")
    end 
    search_string = []

    # Check if Search Keyword is Present & Write it's Query
    if params.has_key?('search') && params[:search].has_key?('value') && params[:search][:value].present?
      search_columns.each do |term|
        search_string << "#{term} ILIKE :search"
      end
      projects = projects.where(search_string.join(' OR '), search: "%#{params[:search][:value]}%")
    end

    projects = projects.page(datatable_page).per(datatable_per_page)
    render json: {
      projects: projects.as_json,
      recordsTotal: projects.count,
      recordsFiltered: projects.total_count
    }
  end 

  def projects_jobs 
    @projectid = params[:id]
  end 
  
  def fetch_projects_jobs 
    @project = Project.find_by(params[:id])
    project_jobs = @project.jobs if @project.present?
    
    jobs = Project.find(params[:projectid]).jobs.order(created_at:"desc")
    search_string = []

    # Check if Search Keyword is Present & Write it's Query
    if params.has_key?('search') && params[:search].has_key?('value') && params[:search][:value].present?
      search_columns.each do |term|
        search_string << "#{term} ILIKE :search"
      end
      jobs = jobs.where(search_string.join(' OR '), search: "%#{params[:search][:value]}%")
    end

    jobs = jobs.page(datatable_page).per(datatable_per_page)
    render json: {
      jobs: jobs.as_json,
      recordsTotal: jobs.count,
      recordsFiltered: jobs.total_count
    }
  end 

  def projects_users 
    @projectid = params[:id]
  end 

  def fetch_projects_users 
    users = Project.find(params[:projectid]).users.order(created_at:"desc")
    search_string = []

    # Check if Search Keyword is Present & Write it's Query
    if params.has_key?('search') && params[:search].has_key?('value') && params[:search][:value].present?
      search_columns.each do |term|
        search_string << "#{term} ILIKE :search"
      end
      users = users.where(search_string.join(' OR '), search: "%#{params[:search][:value]}%")
    end

    users = users.page(datatable_page).per(datatable_per_page)
    render json: {
      users: users.as_json,
      recordsTotal: users.count,
      recordsFiltered: users.total_count
    }
  end 


  def users_projects 
    @userid = params[:id]
  end 

  def fetch_users_projects
    projects = User.find(params[:userid]).projects.order(created_at:"desc")
    search_string = []

    # Check if Search Keyword is Present & Write it's Query
    if params.has_key?('search') && params[:search].has_key?('value') && params[:search][:value].present?
      search_columns.each do |term|
        search_string << "#{term} ILIKE :search"
      end
      projects = projects.where(search_string.join(' OR '), search: "%#{params[:search][:value]}%")
    end

    projects = projects.page(datatable_page).per(datatable_per_page)
    render json: {
      projects: projects.as_json,
      recordsTotal: projects.count,
      recordsFiltered: projects.total_count
    }
  end

  def new 
    @project = Project.new
  end 

  def create 
    @project = Project.new(project_create_params)
    @project.save!
    respond_to do |format|
      if @project.save 
        format.html{ redirect_to projects_url , success: "Project was sucessfully added." }
      else
        format.html{ render :new , status: :unprocessable_entity }
      end 
    end 
  end 

  def edit 
    # authorize! :read, @project
  end 

  def update 
    respond_to do |format|
      if @project.update!(project_update_params)
        ProjectAssignMailer.project_assign(@project).deliver
        format.html { redirect_to projects_url, success: "Project was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end 

  def destroy 
    @project.destroy
   
   respond_to do |format|
      format.html { redirect_to projects_url }
   end
  end 
  private 

  def search_columns
    %w(name)
  end

  def sort_column
    columns = %w(name)
    columns[params[:order]['0'][:column].to_i - 1]
  end

  def set_project 
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound => error
    redirect_to root_path, notice: "You are fetching the records that are not exists in database."
  end 

  def project_create_params 
     params.require(:project).permit(:name, :start_date, :end_date, :is_active, :company_id)
  end 

  def project_update_params 
    params.require(:project).permit(:name, :start_date, :end_date, :is_active, :company_id, user_ids:[])
  end 
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def button_value
    if controller.action_name == "new"
       return "Add Project"
    elsif controller.action_name == "edit"
       return "Update Project"
    else
       return "Submit"
    end
  end
end

app/views/projects/_form.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="row">
      <div class="col-xxl">
        <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5 class="mb-0">Add Project</h5>
          </div>
        <div class="card-body">
          <%= form_with(class: 'project-form', model: (@project), local: true) do |f| %>
            <div class="row mb-3">
              <label class="col-sm-2 col-form-label" for="basic-icon-default-name">Name</label>
                <div class="col-sm-10">
                  <div class="input-group input-group-merge">
                    <span id="basic-icon-default-name2" class="input-group-text">
                    <i class="bx bx-code-block"></i></span>
                      <%= f.text_field :name, id:"basic-icon-default-name", class:"form-control", data: {error: "#errProject1"} %>
                  </div>
                  <span id="errProject1"></span>
                </div>
            </div>
            <div class="row mb-3">
              <label class="col-sm-2 col-form-label" for="html5-start-date-input" >Start Date</label>
                <div class="col-sm-10">
                  <div class="input-group input-group-merge">
                    <span id="basic-icon-default-company2" class="input-group-text">
                      <i class='bx bxs-calendar'></i>
                    </span>
                      <%= f.date_field :start_date, id:"html5-start-date-input", class:"form-control",data:{error: "#errProject2"} %>
                  </div>
                  <span id="errProject2"></span>
                </div>
              </div>
              <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="html5-end-date-input">end_date</label>
                  <div class="col-sm-10">
                    <div class="input-group input-group-merge">
                      <span class="input-group-text">
                        <i class='bx bxs-calendar'></i>
                      </span>
                      <%= f.date_field :end_date, id:"html5-end-date-input", class:"form-control" %>
                    </div>
                  </div>
              </div>
              <div class="row mb-3">
                <label class="col-sm-2 form-label">Status</label>
                  <div class="col-sm-10">
                    <%= f.check_box :is_active, class:"form-check-input", id:"status" %>
                  <label class="form-check-label" for="status">Active</label>
                  </div>
              </div>
              <div class="col-sm-10">
                <%= f.hidden_field :company_id, value: current_user.company_id %>
              </div>
              <div class="row justify-content-end">
                <div class="col-sm-10">
                   <%= f.submit button_value, class:'btn btn-primary'%>
                </div>
                <div class="col-sm-3 project-back-btn">
                   <%= link_to 'Back', projects_path, class:'btn btn-primary mb-2' %>
                </div>
          <% end %>
        </div>
    </div>
  </div>
</div>  

app/views/projects/edit.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="row">
      <div class="col-xxl">
        <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5 class="mb-0">Edit Project</h5>
          </div>
        <div class="card-body">
          <%= form_with(class: 'project-form', model: (@project), local: true) do |f| %>
            <div class="row mb-3">
              <label class="col-sm-2 col-form-label" for="basic-icon-default-name">Name</label>
                <div class="col-sm-10">
                  <div class="input-group input-group-merge">
                    <span id="basic-icon-default-name2" class="input-group-text">
                    <i class="bx bx-code-block"></i></span>
                      <%= f.text_field :name, id:"basic-icon-default-name", class:"form-control" %>
                  </div>
                </div>
            </div>
            <div class="row mb-3">
              <label class="col-sm-2 col-form-label" for="html5-start-date-input" >Start Date</label>
                <div class="col-sm-10">
                  <div class="input-group input-group-merge">
                    <span id="basic-icon-default-company2" class="input-group-text">
                      <i class='bx bxs-calendar'></i>
                    </span>
                      <%= f.date_field :start_date, id:"html5-start-date-input", class:"form-control" %>
                  </div>
                </div>
              </div>
              <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="html5-end-date-input">end_date</label>
                  <div class="col-sm-10">
                    <div class="input-group input-group-merge">
                      <span class="input-group-text">
                        <i class='bx bxs-calendar'></i>
                      </span>
                      <%= f.date_field :end_date, id:"html5-end-date-input", class:"form-control" %>
                    </div>
                  </div>
              </div>
              <div class="row mb-3">
                <label class="col-sm-2 form-label">Status</label>
                  <div class="col-sm-10">
                    <%= f.check_box :is_active, class:"form-check-input", id:"status" %>
                  <label class="form-check-label" for="status">Active</label>
                  </div>
              </div>
              <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="html5-end-assign">Assign To</label>
                  <div class="col-sm-10">
                    <div class="input-group input-group-merge" id="html5-end-assign">
                      <%= f.collection_select(:user_ids, User.all, :id, :first_name, { :prompt => 'Select an Employees' }, { class: 'form-control js-example-basic-multiple',multiple: true}) %>
                    </div>
                  </div>
              </div>
              <div class="col-sm-10">
                <%= f.hidden_field :company_id, value: current_user.company_id %>
              </div>
              <div class="row justify-content-end">
                <div class="col-sm-10">
                   <%= f.submit button_value, class:'btn btn-primary'%>
                </div>
                <div class="col-sm-3 project-back-btn">
                   <%= link_to 'Back', projects_path, class:'btn btn-primary mb-2' %>
                </div>
          <% end %>
        </div>
    </div>
  </div>
</div>
</div>

app/views/projects/fetch_projects_jobs.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
      <h5 class="card-header">Jobs</h5>
      <div class="table-responsive text-nowrap">
        <table class="table" id="projects-jobs-list">
          <caption class="ms-4">
            List of Jobs
          </caption>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
      <h5 class="card-header">Projects</h5>
      <div class="table-responsive text-nowrap">
      <% if can? :create, Project %>
      <div class="col">
          <h4 class="fw-bold float-end m-3"><span class="text-muted fw-light"><a href='/projects/new' class="btn btn-primary mt-1 mb-2 shared-add-btn"><i class='bx bx-plus'></i><span>Add project</span></a></h4>
      </div>
      <% end %>
        <table class="table" id="projects-list" data-userrole="<%= current_user.role %>">
          <caption class="ms-4">
            List of Projects
          </caption>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'form' %>
        

app/views/projects/projects_jobs.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
      <h5 class="card-header">Jobs</h5>
      <div class="table-responsive text-nowrap">
      <%= link_to 'Project Listing', projects_path, class:"btn btn-primary mb-3 project-btn"%>
        <table class="table" id="projects-jobs-list" data-source="<%= fetch_projects_jobs_path(format: :json, projectid: @projectid) %>">
          <caption class="ms-4">
            List of Project Jobs
          </caption>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/projects/projects_users.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
      <h5 class="card-header">Users</h5>
      <div class="table-responsive text-nowrap">
      <%= link_to ' Project Listing', projects_path, class:"btn btn-primary mb-3 project-btn"%>
        <table class="table" id="projects-users-list" data-source="<%= fetch_projects_users_path(format: :json, projectid: @projectid) %>">
          <caption class="ms-4">
            List of Project Users
          </caption>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/projects/users_projects.html.erb
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
      <h4 class="fw-bold py-3 mb-2"><span class="text-muted fw-light"><%= link_to('Employees Listing', users_path, class: 'btn btn-primary float-end') %></h4>
      <h5 class="card-header">Projects</h5>
      <div class="table-responsive text-nowrap">
        <table class="table" id="users-projects-list" data-source="<%= fetch_users_projects_path(format: :json, userid: @userid) %>" >
          <caption class="ms-4">
            List of Users Projects
          </caption>
        </table>
      </div>
    </div>
  </div>
</div>